using System;
using System.Collections.Generic;
using System.Reactive;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Controls.Templates;
using ReactiveUI;
using RogueEssence.Dev.Services;
using RogueEssence.Dev.Views;

namespace RogueEssence.Dev.ViewModels;

public class ReflectedDataPageViewModel : EditorPageViewModel<NodeBase>
{
    public Action<StackPanel> OnLoadAction;
    public Func<StackPanel, Task<bool>> OnOKAction;
    
    private bool _shouldRemoveNode = true;
    
    public ReflectedDataPageViewModel(EditorContext context,
        NodeBase node, Action<EditorPageViewModel> onPageLoad) : base(context, node, onPageLoad)
    {
    }
    
    // Whether to remove the node from the parent when the page is closed
    public void SetRemoveNode(bool remove)
    {
        _shouldRemoveNode = remove;
    }
    
    private bool _isRootPage;
    public bool IsRootPage
    {
        get => _isRootPage;
        private set => this.RaiseAndSetIfChanged(ref _isRootPage, value);
    }

    // If the page is the root page, it will include the "Save All Sub-Windows" button
    public void SetIsRootPage(bool isRoot)
    {
        IsRootPage = isRoot;
    }
    
    public async Task<bool> ApplySave()
    {
        await _context.TabEvents.SaveChildren(this);
        if (AttachedView is ISaveable saveable)
            return await saveable.Save();
        return true;
    }

    public void RemoveNodeFromTree()
    {
        if (_shouldRemoveNode)
        {
            Node.Parent?.SubNodes.Remove(Node);
        }
    }
    public void Close()
    {
        _context.TabEvents.RemoveTab(this);
        RemoveNodeFromTree();
    }
    public override void OnPageRemoved()
    {
        RemoveNodeFromTree();
        base.OnPageRemoved();
    }
    
    // A page that is autogenerated will never be the same page as another page?
    protected override bool IsSamePage(EditorPageViewModel other)
    {
        if (other is not ReflectedDataPageViewModel otherPage)
            return false;
        
        return otherPage.Node.Equals(Node);
    }
}