using System;
using System.Collections.Generic;
using System.Reactive;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Controls.Templates;
using ReactiveUI;
using RogueEssence.Dev.Services;
using RogueEssence.Dev.Views;

namespace RogueEssence.Dev.ViewModels;

public class ReflectedDataPageViewModel : EditorPageViewModel<NodeBase>
{
    
    public Action<StackPanel> OnLoadAction;
    public Func<StackPanel, Task<bool>> OnOKAction;

    // public delegate Task<bool> OKEvent();
    // public OKEvent SelectedOKEvent;

    // public override string Title => "Random Page Info";
    public ReflectedDataPageViewModel(EditorContext context,
        NodeBase node) : base(context, node)
    {
        AddNewNodeAndTabCommand = ReactiveCommand.Create(AddNewNodeAndTabDefault);
    }
    
    public bool isRootPage => Node is not ReflectedDataNode;
    public override void LoadData()
    {
        base.LoadData();
    }


    public async Task<bool> ApplySave()
    {
        await _context.TabEvents.SaveChildren(this);
        if (AttachedView is ISaveable saveable)
            return await saveable.Save();
        return true;
    }
    public void Close()
    {
        Node.Parent?.SubNodes.Remove(Node);
        _context.TabEvents.RemoveTab(this);
    }

    public ReactiveCommand<Unit, Unit> AddNewNodeAndTabCommand { get; }
 
    public void AddNewNodeAndTabDefault()
    {
        NodeBase node = _context.NodeFactory.CreateReflectedDataNode<ReflectedDataPageViewModel>("New Node [TODO Change Title]", "Icons.PaintBrushFill");
        Node.SubNodes.Add(node);
        var editor = _context.PageFactory.CreatePage<ReflectedDataPageViewModel>(node);
        if (editor != null)
        {
            editor.SetPageTitle("New Node [TODO Change Title]", Node.Icon);
            _context.TabEvents.AddChildPage(this, editor);
        }
    }
    
    public event EventHandler Closed;

    public List<ReflectedDataPageViewModel> Children;

    // public void RegisterChild(ReflectedDataPageViewModel child)
    // {
    //     Children.Add(child);
    //     child.Closed += (object sender, EventArgs e) =>
    //     {
    //         Children.Remove(child);
    //         TabClosed?.Invoke(this, EventArgs.Empty);
    //     };
    // }
    
    public void RegisterChild(ReflectedDataPageViewModel child)
    {
        Children.Add(child);
    }
    
    public void UnregisterChild(ReflectedDataPageViewModel child)
    {
        Children.Remove(child);
        Closed?.Invoke(this, EventArgs.Empty);
    }
    
    // public async Task SaveChildren()
    // {
    //     for (int ii = Children.Count - 1; ii >= 0; ii--)
    //     {
    //         DataEditForm dataEditor = children[ii];
    //         if (dataEditor != null)
    //         {
    //             await dataEditor.SaveChildren();
    //             if (dataEditor.SelectedOKEvent != null)
    //                 await dataEditor.SelectedOKEvent.Invoke();
    //         }
    //     }
    // }
    //

    // Dummy test
    // public void AddNewNodeAndTab()
    // {
    //     NodeBase node = NodeFactory.CreateOpenEditorNode<ReflectedDataPageViewModel>("New Node", "Icons.PaintBrushFill");
    //     Node.SubNodes.Add(node);
    //     var editor = PageFactory.CreatePage<ReflectedDataPageViewModel>(node);
    //     if (editor != null)
    //     {
    //         TabEvents.AddTopLevelTab(editor);
    //     }
    // }
    
    public override void OnPageRemoved()
    {
        Node.Parent?.RemoveNode(Node);
        base.OnPageRemoved();
    }
    
    // A page that is autogenerated will never be the same page as another page?
    protected override bool IsSamePage(EditorPageViewModel other)
    {
        if (other is not ReflectedDataPageViewModel otherPage)
            return false;
        
        return otherPage.Node.Equals(Node);
    }
}