using RogueEssence.Dev.Services;

namespace RogueEssence.Dev.ViewModels;

public class ReflectedDataPageViewModel : EditorPageViewModel<NodeBase>
{
    
    // TODO:
    // A page that is autogenerated will never be the same page as another page?
    protected override bool IsSamePage(EditorPageViewModel other)
    {
        if (other is not ReflectedDataPageViewModel otherPage)
            return false;
        return otherPage.Node.Equals(Node);
    }

    // public override string Title => "Random Page Info";
    public ReflectedDataPageViewModel(NodeFactory nodeFactory, PageFactory pageFactory, TabEvents tabEvents, IDialogService dialogService,
        NodeBase node) : base(nodeFactory, pageFactory, tabEvents, dialogService, node)
    {
    }
}