<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RogueEssence\RogueEssence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.8" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.8" />
    <PackageReference Include="Avalonia.Controls.TreeDataGrid" Version="11.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.8" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.8" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    <PackageReference Include="ResXResourceReader.NetStandard" Version="1.0.1" />
    <PackageReference Include="Tabalonia" Version="0.10.7" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="DataEditor\RankedCollectionBox.axaml.cs">
      <DependentUpon>RankedCollectionBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\RangeDictBox.axaml.cs">
      <DependentUpon>RangeDictBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\Editors\RogueEssence\Tiles\TileEditWindowView.axaml.cs">
      <DependentUpon>TileEditForm.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\Editors\RogueEssence\Tiles\TileBox.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\ParentForm.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\CategorySpawnBox.axaml.cs">
      <DependentUpon>CategorySpawnBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\SpawnListViewBox.axaml.cs">
      <DependentUpon>SpawnListViewBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\SpawnRangeListBox.axaml.cs">
      <DependentUpon>SpawnRangeListBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\SpawnListBox.axaml.cs">
      <DependentUpon>SpawnListBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\PriorityListBox.axaml.cs">
      <DependentUpon>PriorityListBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\DictionaryBox.axaml.cs">
      <DependentUpon>DictionaryBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\CollectionBox.axaml.cs">
      <DependentUpon>CollectionBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\DataEditForm.axaml.cs">
      <DependentUpon>DataEditForm.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\ClassBox.axaml.cs">
      <DependentUpon>ClassBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\Layers\GroundLayerWindow.axaml.cs">
      <DependentUpon>GroundLayerWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabDecorations.axaml.cs">
      <DependentUpon>MapTabDecorations.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\Teams\TeamWindow.axaml.cs">
      <DependentUpon>TeamWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Testing\TextTestForm.axaml.cs">
      <DependentUpon>TextTestForm.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\DevForm\DevTabConstants.axaml.cs">
      <DependentUpon>DevTabConstants.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\DevForm\DevTabMods.axaml.cs">
      <DependentUpon>DevTabMods.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\GroundTabScript.axaml.cs">
      <DependentUpon>GroundTabScript.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\Layers\EntityLayerWindow.axaml.cs">
      <DependentUpon>EntityLayerWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\Layers\AnimLayerWindow.axaml.cs">
      <DependentUpon>AnimLayerWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\Layers\MapLayerWindow.axaml.cs">
      <DependentUpon>MapLayerWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\GroundTabDecorations.axaml.cs">
      <DependentUpon>GroundTabDecorations.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabSpawns.axaml.cs">
      <DependentUpon>MapTabSpawns.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabEntrances.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabItems.axaml.cs">
      <DependentUpon>MapTabItems.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabEffects.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabProperties.axaml.cs">
      <DependentUpon>MapTabProperties.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabEntities.axaml.cs">
      <DependentUpon>MapTabEntities.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabTiles.axaml.cs">
      <DependentUpon>MapTabTiles.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabTerrain.axaml.cs">
      <DependentUpon>MapTabTerrain.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MapEditForm\MapTabTextures.axaml.cs">
      <DependentUpon>MapTabTextures.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SearchListBox.axaml.cs">
      <DependentUpon>SearchListBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\GroundTabEntities.axaml.cs">
      <DependentUpon>GroundTabEntities.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\GroundTabWalls.axaml.cs">
      <DependentUpon>GroundTabWalls.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\GroundTabTextures.axaml.cs">
      <DependentUpon>GroundTabTextures.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\GroundEditForm.axaml.cs">
      <DependentUpon>GroundEditForm.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\UserControls\TeamBox.axaml.cs">
      <DependentUpon>TeamBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\UserControls\LayerBox.axaml.cs">
      <DependentUpon>LayerBox.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GroundEditForm\EntityBrowser.axaml.cs">
      <DependentUpon>EntityBrowser.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\Editors\RogueEssence\Tiles\AutotileBrowser.axaml.cs">
      <DependentUpon>AutotileBrowser.axaml</DependentUpon>
    </Compile>
    <Compile Update="DataEditor\Editors\RogueEssence\Tiles\TileBrowser.axaml.cs">
      <DependentUpon>TileBrowser.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Pages\MapEditPage\MapEditPageView.axaml.cs">
      <DependentUpon>MapEditPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\GroundEditPage\GroundEditPageView.axaml.cs">
      <DependentUpon>GroundEditPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DevControlPage\DevControlPageView.axaml.cs">
      <DependentUpon>DevControlPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DevControlPage\DevTabGame.axaml.cs">
      <DependentUpon>DevTabGame.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DevControlPage\DevTabPlayer.axaml.cs">
      <DependentUpon>DevTabPlayer.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DevControlPage\DevTabTravel.axaml.cs">
      <DependentUpon>DevTabTravel.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DevControlPage\DevTabScript.axaml.cs">
      <DependentUpon>DevTabScript.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DataListPageView.axaml.cs">
      <DependentUpon>DataListPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\ModConfigPageView.axaml.cs">
      <DependentUpon>ModConfigPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\ModListPageView.axaml.cs">
      <DependentUpon>ModListPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\RandomInfoPageView.axaml.cs">
      <DependentUpon>RandomInfoPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\ReflectedDataPageView.axaml.cs">
      <DependentUpon>ReflectedDataPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\SpeciesEditPageView.axaml.cs">
      <DependentUpon>SpeciesEditPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\SpritePageView.axaml.cs">
      <DependentUpon>SpritePageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\StringEditPageView.axaml.cs">
      <DependentUpon>StringEditPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DevForm\CaptionButtons.axaml.cs">
      <DependentUpon>CaptionButtons.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DevForm\DevForm.axaml.cs">
      <DependentUpon>DevForm.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DevForm\ModSwitcherView.axaml.cs">
      <DependentUpon>ModSwitcherView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DevForm\TabBarView.axaml.cs">
      <DependentUpon>TabBarView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DevForm\TabSwitcherView.axaml.cs">
      <DependentUpon>TabSwitcherView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\UserControls\IconText.axaml.cs">
      <DependentUpon>IconText.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\AnimChoiceWindowView.axaml.cs">
      <DependentUpon>AnimChoiceWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\PreferencesWindowView.axaml.cs">
      <DependentUpon>PreferencesWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\RenameWindowView.axaml.cs">
      <DependentUpon>RenameWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\MessageBoxWindowView.axaml.cs">
      <DependentUpon>MessageBoxWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\ModNameWindowView.axaml.cs">
      <DependentUpon>ModNameWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\MapResizeWindowView.axaml.cs">
      <DependentUpon>MapResizeWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\MapRetileWindowView.axaml.cs">
      <DependentUpon>MapRetileWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\MapLayerWindowView.axaml.cs">
      <DependentUpon>MapLayerWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\DialogBoxes\ReflectedDataWindowView.axaml.cs">
      <DependentUpon>ReflectedDataWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="Views\Pages\GroundEditPage\EntityBrowser.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabDecorations.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabEntities.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabProperties.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabScript.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabStrings.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabTextures.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\GroundTabWalls.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\Layers\AnimLayerWindow.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\Layers\EntityLayerWindow.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\Layers\GroundLayerWindow.axaml" />
    <AdditionalFiles Include="Views\Pages\GroundEditPage\Layers\MapLayerWindow.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabDecorations.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabEffects.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabEntities.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabEntrances.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabItems.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabProperties.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabSpawns.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabTerrain.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabTextures.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\MapTabTiles.axaml" />
    <AdditionalFiles Include="Views\Pages\MapEditPage\Teams\TeamWindow.axaml" />
  </ItemGroup>
</Project>
